In [1]:
print("hello world")
print("hello world")
print("hello world")

hello world
hello world
hello world


In [4]:
import tensorflow as tf
import numpy as np

In [7]:
x = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
y = tf.constant([[0, 1], [1, 0]], dtype=tf.float32)
z = x+y
print(z)

tf.Tensor(
[[1. 3.]
 [4. 4.]], shape=(2, 2), dtype=float32)


In [9]:
x1 = tf.ones(shape=[3,2], dtype=tf.float32)
x2 = tf.random.normal(shape=(10, 2), mean=0.0, stddev=1.0, dtype=tf.float32)

In [13]:
x = tf.constant([[3.2, -1], [5.1, 1], [-1.7, 2.0]])
y = tf.transpose(x)
z1 = x@y
print(z1.numpy())

[[11.240001  15.32      -7.44     ]
 [15.32      27.009998  -6.67     ]
 [-7.44      -6.67       6.8900003]]


In [14]:
z2 = tf.nn.softmax(z1)

In [15]:
print(z2)

tf.Tensor(
[[1.6626373e-02 9.8337364e-01 1.2828506e-10]
 [8.3771147e-06 9.9999166e-01 2.3602503e-15]
 [5.9780467e-07 1.2911177e-06 9.9999809e-01]], shape=(3, 3), dtype=float32)


In [17]:
v1 = tf.Variable([[1, 2, 3], [4, 5, 6]], dtype=tf.float32)
v2 = tf.Variable([[1, 2, 3], [4, 5, 6]], dtype=tf.float32)
v1[0].assign([3, 3, 3])
print(v1)
v1.assign_add([[1, 1, 1], [1, 1, 1]])
print(v1)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[3., 3., 3.],
       [4., 5., 6.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[4., 4., 4.],
       [5., 6., 7.]], dtype=float32)>


In [26]:
x = tf.Variable(3.0)
with tf.GradientTape() as tape:
    y = x ** 2
    
dy_dx = tape.gradient(y, x)
print(y)
print(dy_dx)

tf.Tensor(9.0, shape=(), dtype=float32)
tf.Tensor(6.0, shape=(), dtype=float32)


In [35]:
leanring_rate = 0.1
w = tf.Variable(0, dtype=tf.float32)

def train_step(x):
    with tf.GradientTape() as tape:
        cost = x * (w**2 - 10*w + 25)
    dw = tape.gradient(cost, w)
    w.assign_sub(leanring_rate * dw)
    return cost

for i in range(200):
    cost = train_step(0.5)
    print(f"step: {i}, cost: {cost}, w: {w.numpy()}")

step: 0, cost: 12.5, w: 0.5
step: 1, cost: 10.125, w: 0.9500000476837158
step: 2, cost: 8.201250076293945, w: 1.3550000190734863
step: 3, cost: 6.643012523651123, w: 1.7195000648498535
step: 4, cost: 5.380840301513672, w: 2.0475499629974365
step: 5, cost: 4.358480453491211, w: 2.342794895172119
step: 6, cost: 3.530369758605957, w: 2.608515501022339
step: 7, cost: 2.8595991134643555, w: 2.8476638793945312
step: 8, cost: 2.3162755966186523, w: 3.0628974437713623
step: 9, cost: 1.8761825561523438, w: 3.2566077709198
step: 10, cost: 1.5197086334228516, w: 3.4309470653533936
step: 11, cost: 1.2309627532958984, w: 3.5878524780273438
step: 12, cost: 0.9970798492431641, w: 3.729067325592041
step: 13, cost: 0.8076353073120117, w: 3.8561606407165527
step: 14, cost: 0.6541843414306641, w: 3.9705445766448975
step: 15, cost: 0.5298900604248047, w: 4.073490142822266
step: 16, cost: 0.4292106628417969, w: 4.166141033172607
step: 17, cost: 0.3476600646972656, w: 4.2495269775390625
step: 18, cost: 0.28